V06 review suggestions
NLnetLabs/draft-toorop-dnsop-dns-catalog-zones pull request #48
Opened 2022-06-15 15:15 UTC by mind04

My review for #45

1. NS records are sometime useful for the implementation. Ignore them completely is not possible.
2. Be more clear that a catalog consumer should ignore ALL Records it does not understand
3. Try to improve the wording about coo
4. Group properties are agreed between the consumer and producer operator. There is no need to be this restrictive about the exact format in the draft. This pull is also adding multiple groups per zone. This will make it possible to send the same catalog to multiple operators with different group requirement. This will simplify management of catalog zones greatly since it no longer necessary to create a catalog per operator (and keep those in sync).

2022-06-22 14:24 UTC, wtoorop commented on draft-ietf-dnsop-dns-catalog-zones.md
> +Catalog consumers SHOULD ignore records they do not understand.
I like the change of the first line in the commit, but not the second. 
We already stated that "Catalog consumers SHOULD ignore any RR in the catalog zone which is meaningless or useless to the implementation." in the Description section. So this line is just a confirmation that this thus also holds for properties.

```suggestion
Catalog consumers SHOULD ignore properties they do not understand.
```

@mind04 WDYT?

2022-06-22 14:41 UTC, wtoorop requested changes
@mind04 , I have already pushed the first and the third commit to the version-06 PR.

The second commit I'd like to accept partly, so I have done a suggestion that you can accept.

The fourth commit extending the `group` property needs discussion with @libor-peltan-cznic . I can see one thing which needs to be addressed already: What should a consumer do that sees  more than one property it does understand? Apply one, apply all of them or apply none of them.

Anyway, if you accept the suggestion I did for the second commit, I will push that already to the version-06 branch and this PR can remain to discuss and review the extension on the `group` property.

2022-06-22 15:37 UTC, mind04 commented
> The fourth commit extending the `group` property needs discussion with @libor-peltan-cznic . I can see one thing which needs to be addressed already: What should a consumer do that sees more than one property it does understand? Apply one, apply all of them or apply none of them.

It is not up to us to determine what to do with multiple group properties. This is something operators of consumers and producers should agree on. With the proper agreements (send only one group property) all current implementations of group are still fully compatible with this modification. While this modification is adding new possibilities for new implementations.

2022-06-22 15:59 UTC, libor-peltan-cznic commented
While it seems reasonable and useful to extend the number of possible groups per member from one to more, I feel a bit concerned about their total amount.

Even if we lift the requirements in the way that it's up to the consumer what he does when he does recognize some subset of them...

Might it be harmful if there are somehow too many of them? Shall we somehow consider it?

2022-06-23 07:11 UTC, Habbie commented
> While it seems reasonable and useful to extend the number of possible groups per member from one to more, I feel a bit concerned about their total amount.

Given that the semantics of group are entirely up to individual vendors and operators, I don't think the draft should be limiting the number.

2022-07-05 13:48 UTC, merged